name: xyloteka
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  another_flushbar: ^1.10.22
  auto_route: ^2.1.0
  bloc: ^7.0.0
  dartz: ^0.10.0-nullsafety.2
  firebase_auth: ^1.2.0
  firebase_core: ^1.2.0
  flutter_bloc: ^7.0.0
  freezed_annotation: ^0.14.2
  get_it: ^7.1.3
  google_sign_in: ^5.0.3
  http: ^0.13.3
  injectable: ^1.4.1
  kt_dart: ^0.9.1
  shared_preferences: ^2.0.6
  uuid: ^3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^2.1.0
  bloc_test: ^8.0.0
  build_runner: ^2.0.3
  freezed: ^0.14.2
  injectable_generator: ^1.4.1
  mocktail: ^0.1.0
  very_good_analysis: ^2.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/bg.png
    - assets/images/icon.png
